spring.application.name=RagToolAgentChatbot
spring.profiles.active=dev

# Railway detects PORT automatically
server.port=${PORT:8080}

logging.level.org.springframework.ai.chat.client.advisor=INFO
logging.level.org.springframework.ai=INFO

