spring.application.name=RagToolAgentChatbot
spring.profiles.active=dev

# Railway detects PORT automatically
server.port=${PORT:8080}

logging.level.org.springframework.ai.chat.client.advisor=INFO
logging.level.org.springframework.ai=INFO

# application.properties
server.servlet.headers.cache-control=public,max-age=0
server.servlet.headers.x-frame-options=DENY
server.servlet.headers.x-xss-protection=1; mode=block
server.servlet.headers.x-content-type-options=nosniff

