spring.application.name=RagToolAgentChatbot
spring.profiles.active=dev

# Railway detects PORT automatically
server.port=${PORT:8080}

logging.level.org.springframework.ai.chat.client.advisor=INFO
logging.level.org.springframework.ai=INFO


spring.ai.chat.memory.repository.jdbc.initialize-schema=always


#######################################
## Spring AI observability settings
#######################################
#
#spring.ai.tools.observations.include-content=true
#
### Include the Chatclient input in observations
#spring.ai.chat.client.observation.log-input=true
#
### Include the VectorStore query and response in observations
#spring.ai.vectorstore.observations.log-query-response=true
#
### Include prompt and completion contents in observations
#spring.ai.chat.observations.log-prompt=true
#spring.ai.chat.observations.log-completion=true
#
### Include error logging in observations (note: not needed for Spring Web apps)
#spring.ai.chat.observations.include-error-logging=true
#
#logging.level.org.springframework.ai.chat.observation=DEBUG